Add in some defaults and simplify for what I am doing

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -32,21 +32,21 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+#      - name: Detect package manager
+#        id: detect-package-manager
+#        run: |
+#          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+#            echo "manager=yarn" >> $GITHUB_OUTPUT
+#            echo "command=install" >> $GITHUB_OUTPUT
+#            exit 0
+#          elif [ -f "${{ github.workspace }}/package.json" ]; then
+#            echo "manager=npm" >> $GITHUB_OUTPUT
+##            echo "command=ci" >> $GITHUB_OUTPUT
+#            exit 0
+#          else
+#            echo "Unable to determine package manager"
+#            exit 1
+#          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
@@ -70,9 +70,11 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-nuxt-build-
       - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+        #run:  ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+        run: npm install #--production=false
       - name: Static HTML export with Nuxt
-        run: ${{ steps.detect-package-manager.outputs.manager }} run generate
+        #run: ${{ steps.detect-package-manager.outputs.manager }} run generate
+        run: npm run generate
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
